const constants = {
    SORT_BAKERY: "SORT_BAKERY",
    ADD_BAKERY: "ADD_BAKERY",
    CHANGE_COUNT: "CHANGE_COUNT",
    REMOVE_BAKERY: "REMOVE_BAKERY",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    ADD_COUNT: "ADD_COUNT",
    DECREASE_COUNT: "DECREASE_COUNT",
    SHOW_CARD: "SHOW_CARD",
    FILTER_PRODUCTS: "FILTER_PRODUCTS"
}

export default constants;